# Generated by Django 5.1.2 on 2024-12-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_avatar_alter_user_phone_number_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
