# Generated by Django 5.1.2 on 2024-12-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_delete_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Укажите страну проживания",
                max_length=100,
                null=True,
                verbose_name="Token",
            ),
        ),
    ]
