# Generated by Django 5.1.2 on 2024-12-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.IntegerField(),
        ),
    ]
